

esphome:
 name: kitchensensor
 platform: esp8266
 board: d1_mini

wifi:
 ssid: 'network-id'
 password: 'network-password'

api:
 password: 'api-password'

ota:
 password: 'ota-password'

binary_sensor:
 - platform: status
   name: "Dish Washer"
 - platform: gpio
   pin: D2
   name: "washer"
   device_class: vibration
   filters:
   - delayed_on: 10ms
   - delayed_off: 5min

  - platform: gpio
    pin: D2
    name: "Kitchen Motion Sensor"
    device_class: motion

sensor:
  - platform: dht
    pin: D5
    model: DHT11
    temperature:
      name: "Temperature Kitchen"
    humidity:
      name: "Humidity Kitchen"
    update_interval: 60s
